namespace Pruner.Core;

public enum Language
{
    Luau,
    Python,
    JavaScript,
    TypeScript,
    CSharp,
    Sql,
    Ruby,
    Go,
    Kotlin,
    Swift,
    Bash,
    Rust,
    Html,
    Css,
    Php,
    Java,
    C,
    Cpp,
    Dart,
    PowerShell,
    Scala,
    R,
    Perl,
    Haskell,
    Elixir,
}

public static class LanguageDetector
{
    private static readonly Dictionary<string, Language> ExtensionMap =
        new(StringComparer.OrdinalIgnoreCase)
        {
            { ".lua",  Language.Luau },
            { ".luau", Language.Luau },
            { ".py",   Language.Python },
            { ".pyw",  Language.Python },
            { ".js",   Language.JavaScript },
            { ".mjs",  Language.JavaScript },
            { ".cjs",  Language.JavaScript },
            { ".ts",   Language.TypeScript },
            { ".mts",  Language.TypeScript },
            { ".cs",   Language.CSharp },
            { ".sql",  Language.Sql },
            { ".rb",       Language.Ruby },
            { ".rake",     Language.Ruby },
            { ".gemspec",  Language.Ruby },
            { ".go",       Language.Go },
            { ".kt",       Language.Kotlin },
            { ".kts",      Language.Kotlin },
            { ".swift",    Language.Swift },
            { ".sh",       Language.Bash },
            { ".bash",     Language.Bash },
            { ".zsh",      Language.Bash },
            { ".fish",     Language.Bash },
            { ".rs",       Language.Rust },
            { ".html",     Language.Html },
            { ".htm",      Language.Html },
            { ".css",      Language.Css },
            { ".php",      Language.Php },
            { ".php8",     Language.Php },
            { ".java",     Language.Java },
            { ".c",        Language.C },
            { ".h",        Language.C },
            { ".cpp",      Language.Cpp },
            { ".cc",       Language.Cpp },
            { ".cxx",      Language.Cpp },
            { ".hpp",      Language.Cpp },
            { ".hxx",      Language.Cpp },
            { ".dart",     Language.Dart },
            { ".ps1",      Language.PowerShell },
            { ".psm1",     Language.PowerShell },
            { ".psd1",     Language.PowerShell },
            { ".scala",    Language.Scala },
            { ".sbt",      Language.Scala },
            { ".r",        Language.R },
            { ".rmd",      Language.R },
            { ".pl",       Language.Perl },
            { ".pm",       Language.Perl },
            { ".hs",       Language.Haskell },
            { ".lhs",      Language.Haskell },
            { ".ex",       Language.Elixir },
            { ".exs",      Language.Elixir },
        };

    public static bool TryDetect(string extension, out Language language) =>
        ExtensionMap.TryGetValue(extension, out language);

    public static IEnumerable<string> SupportedExtensions => ExtensionMap.Keys;

    public static string DisplayName(Language language) => language switch
    {
        Language.Luau       => "Lua / Luau",
        Language.Python     => "Python",
        Language.JavaScript => "JavaScript",
        Language.TypeScript => "TypeScript",
        Language.CSharp     => "C#",
        Language.Sql        => "SQL",
        Language.Ruby       => "Ruby",
        Language.Go         => "Go",
        Language.Kotlin     => "Kotlin",
        Language.Swift      => "Swift",
        Language.Bash       => "Bash / Shell",
        Language.Rust       => "Rust",
        Language.Html       => "HTML",
        Language.Css        => "CSS",
        Language.Php        => "PHP",
        Language.Java       => "Java",
        Language.C          => "C",
        Language.Cpp        => "C++",
        Language.Dart       => "Dart",
        Language.PowerShell => "PowerShell",
        Language.Scala      => "Scala",
        Language.R          => "R",
        Language.Perl       => "Perl",
        Language.Haskell    => "Haskell",
        Language.Elixir     => "Elixir",
        _                   => language.ToString(),
    };
}